-- MySQL Script generated by MySQL Workbench
-- sex 23 mai 2025 22:37:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userSector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userSector` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `idSector` INT NOT NULL,
  `userLider` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_sector_idx` (`idSector` ASC) VISIBLE,
  INDEX `fk_user_userLider_idx` (`userLider` ASC) VISIBLE,
  CONSTRAINT `fk_user_sector`
    FOREIGN KEY (`idSector`)
    REFERENCES `mydb`.`userSector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_userLider`
    FOREIGN KEY (`userLider`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`history` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userHistory` (
  `idUser` INT NOT NULL,
  `idOperations` INT NOT NULL,
  INDEX `fk_user_history_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_history_user_idx` (`idOperations` ASC) VISIBLE,
  CONSTRAINT `fk_user_history`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_user`
    FOREIGN KEY (`idOperations`)
    REFERENCES `mydb`.`history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historyProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historyProduct` (
  `idHistory` INT NOT NULL,
  `idProduct` INT NOT NULL,
  INDEX `fk_history_product_idx` (`idProduct` ASC) VISIBLE,
  INDEX `fk_product_history_idx` (`idHistory` ASC) VISIBLE,
  CONSTRAINT `fk_history_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_history`
    FOREIGN KEY (`idHistory`)
    REFERENCES `mydb`.`history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productVariant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productVariant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variant_product_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_variant_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
